# cargo

# [[file:~/Workspace/Programming/structure-predication/trajectory-analysis/trajectory.note::*cargo][cargo:1]]
[package]
name = "trajectory-analysis"
version = "0.1.2"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
petgraph = "0.4"
clap = "2"
cgmath = "0.17"

[dev-dependencies]
approx = "0.3"
# cargo:1 ends here
