# cargo

# [[file:~/Workspace/Programming/structure-predication/trajectory-analysis/trajectory.note::*cargo][cargo:1]]
[package]
name = "trajectory-analysis"
version = "0.1.6"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
serde = {version="1", features = ["derive"]}
clap = "2"
indicatif = "0.13"
streaming-stats = "0.2"
text-parser = { version = "0.1.1", package = "gchemol-parser" }
guts = { version = "0.1", package="gchemol-gut" }
gchemol = { version = "0.0.40", features=["adhoc"]}

# TODO: remove
itertools = "0.8"
petgraph = "0.5"
gchemol_old = {git = "https://github.com/ybyygu/gchemol.git", package="gchemol"}
structopt = "0.2"
quicli = "0.4"                  # TODO: remove
cgmath = "0.17"                 # TODO: remove


[dev-dependencies]
approx = "0.3"
# cargo:1 ends here
